### ISSUE TITLE
Problem installing VLEIsoTracer

### ISSUE THREAD

**Issue by mina-shahrooz** [usnistgov/isochoric#1]
Hello

I had problem installing this package.  I pip installed `cmake` first.
I downloaded the codes and put them in site-packages folder of anaconda. Then I ran `cmd`, switched to the folder and ran `python setup.py install`. And I received the error:
```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```
So, I couldn't install `VLEIsoTracer`. I am sorry if this question is out of the scope of the topic. I just thought if others had the same problem, there might be a hint how to solve this issue. I have searched for these errors and haven't been successful in fixing the errors.
![image](https://user-images.githubusercontent.com/46826765/112773314-dcfa7500-9035-11eb-873d-0d54c593b61e.png)

**Comment by ianhbell** [comment]
You need to install a compiler.  In this case I believe you need Visual Studio, usually the express or community versions are enough.

**Comment by mina-shahrooz** [comment]
I was unable to install this package. So, I was wondering if the calculations in this package are the same as REFPROP package, so I can create my own phase envelope (P-T-x) for a binary mixture. My goal is to identify the mixtures that are running into instability of VLE solution. 
Taking from RFFPROP documentation:

> Parameters in the HMX.BNC file, which, for a binary mixture, are close for Type I mixtures, but for a multi-component or non-Type I mixture, can be significantly wrong. Such mixtures, including many with hydrogen, helium, or water, may not have Type I critical behavior, that is they do not have a continuous critical line from one pure component to the other. The estimated critical parameters specified in the Substance/Fluid Information screen for these types of mixtures will not be displayed. 

As the information I found on different mixture types, Van Konynenburg and Scott introduced the concept _"class"_ as well as _"type"_. Class 1 mixtures (types I and II) possess a continuous critical curve from one pure fluid critical point to the other, whereas class 2 mixtures (types III, IV and V) do not. Type I mixtures have a continuous vapor-liquid critical curve without any liquid-liquid immiscibility. While, type II mixtures have a three-phase line, L1L2V in addition to continuous vapor-liquid critical curve. So, I am wondering in REFPROP documentation you meant type 1 or class 1? Because type II (part of class 1) has also continuous LV critical line. I know REFPROP does not provide LLE information, but is the VLE information for type II by REFPROP valid? And is there any way I can know a specific mixture has LLE line with REFPROP or not (not the exact information, just to know if it exists or not)?

Thanks

**Comment by ianhbell** [comment]
As I said, you need to install a compiler... Did you have other issues than that? I can also put together a binary wheel for you if you can tell me your operating system, version of python, bitness.

And no, the code in this repository is not the same as in REFPROP (which is why this repository exists) and is MUCH more reliable for p-x diagrams.  You should see some of the crazy things that used to come out of REFPROP p-x diagrams.  

In the tracer, it will tell you when the current solution is unstable, by looking at the eigenvectors of the Hessian of the residual Helmholtz density (recommend to read the referenced paper).

**Comment by mina-shahrooz** [comment]
Thanks for your reply. I have installed visual studio, but I receive the same error.

```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by ianhbell** [comment]
Recommend to delete your build folder and try again.

**Comment by mina-shahrooz** [comment]
Thank you very much. I could pass that error, but still struggling with installation. I have downloaded the external codes separately and put them in their files.
The errors I get are:

```
-- CoolProp version: 6.3.1dev
CMake Warning (dev) at externals/CoolProp/CMakeLists.txt:252 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at externals/CoolProp/CMakeLists.txt:253 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at externals/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Cannot find source file:
```
I am sorry to bother you. 

The full installation result is:
```
C:\Users\minash\Anaconda3\Lib\site-packages\isochoric-master>python setup.py install
running install
running bdist_egg
running egg_info
writing VLEIsoTracer.egg-info\PKG-INFO
writing dependency_links to VLEIsoTracer.egg-info\dependency_links.txt
writing top-level names to VLEIsoTracer.egg-info\top_level.txt
reading manifest file 'VLEIsoTracer.egg-info\SOURCES.txt'
writing manifest file 'VLEIsoTracer.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- COOLPROP_INSTALL_PREFIX=C:/Users/minash/Anaconda3/Lib/site-packages/isochoric-master/externals/CoolProp/install_root
-- CoolProp version: 6.3.1dev
CMake Warning (dev) at externals/CoolProp/CMakeLists.txt:252 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at externals/CoolProp/CMakeLists.txt:253 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: C:/Users/minash/Anaconda3/python.exe (found suitable version "3.8.5", minimum required is "2.7")
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Library compilation detected:
-- Creating CoolProp, a 64-bit library
-- CMAKE_SYSTEM_NAME: Windows
-- COOLPROP_STATIC_LIBRARY: true
-- COOLPROP_SHARED_LIBRARY: OFF
-- COOLPROP_OBJECT_LIBRARY: OFF
-- CONVENTION:
-- COOLPROP_LIBRARY_HEADER: include/CoolPropLib.h
-- COOLPROP_LIBRARY_SOURCE: src/CoolPropLib.cpp
-- COMPILE_FLAGS:
-- LINK_FLAGS:
-- Found PythonInterp: C:/Users/minash/Anaconda3/python.exe (found version "3.8.5")
-- Found PythonLibs: C:/Users/minash/Anaconda3/libs/Python38.lib
-- pybind11 v2.3.dev0
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- LTO enabled
-- Configuring done
CMake Error at externals/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Cannot find source file:

    C:/Users/minash/Anaconda3/Lib/site-packages/isochoric-master/externals/CoolProp/externals/Eigen/debug/msvc/eigen.natvis

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:21 (pybind11_add_module)


-- Generating done
-- Build files have been written to: C:/Users/minash/Anaconda3/Lib/site-packages/isochoric-master/build/temp.win-amd64-3.8/Release
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    setup(
  File "C:\Users\minash\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\minash\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\minash\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\minash\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\minash\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\minash\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\minash\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\minash\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\minash\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\minash\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "C:\Users\minash\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\minash\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\minash\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\minash\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\minash\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\minash\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 34, in run
    self.build_extension(ext)
  File "setup.py", line 58, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Users\minash\Anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\minash\\Anaconda3\\Lib\\site-packages\\isochoric-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\minash\\Anaconda3\\Lib\\site-packages\\isochoric-master\\build\\lib.win-amd64-3.8', '-DPYTHON_EXECUTABLE=C:\\Users\\minash\\Anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\minash\\Anaconda3\\Lib\\site-packages\\isochoric-master\\build\\lib.win-amd64-3.8', '-A', 'x64']' returned non-zero exit status 1.
```

**Comment by ianhbell** [comment]
You need to checkout the code with: ``git clone --recursive https://github.com/usnistgov/isochoric`` to make sure all the external dependencies are included properly .  They weren't in your case, which is why it didn't work.

**Comment by mina-shahrooz** [comment]
Thank you very much. With your help, I could install it.
I am going to close the issue. Thanks again.
